### ISSUE TITLE
Build failed through homebrew

### ISSUE THREAD

**Issue by hydra1983** [michaeleisel/zld#99] opened 2022-01-07 10:02 UTC
```bash
brew install michaeleisel/zld/zld                                                                                       15:01   07.01.22
==> Installing zld from michaeleisel/zld
==> Downloading https://github.com/michaeleisel/zld/archive/refs/heads/homebrew-fixes-1.3.3.zip
Already downloaded: /Users/xxxxxx/Library/Caches/Homebrew/downloads/fe560f9185d8fdf96707287aa78ff219507f3143158e1c208848dc1f86503952--zld-homebrew-fixes-1.3.3.zip
==> make clean
==> make build_homebrew
Last 15 lines from /Users/xxxxxx/Library/Logs/Homebrew/zld/02.make:
    export LANG\=en_US.US-ASCII
    clang -x c++ -target x86_64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c++1z -stdlib\=libc++ -Wno-trigraphs -fpascal-strings -O3 -fno-common -mdynamic-no-pic -Wno-missing-field-initializers -Wmissing-prototypes -Wunreachable-code -Wno-non-virtual-dtor -Woverloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wno-uninitialized -Wunknown-pragmas -Wno-shadow -Wfour-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wsign-compare -Wno-shorten-64-to-32 -Wnewline-eof -Wno-c++11-extensions -DLD_VERS\=\"ld64-\" -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Wno-invalid-offsetof -g -msse4.2 -Wno-sign-conversion -Winfinite-recursion -Wmove -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -iquote /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-generated-files.hmap -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-own-target-headers.hmap -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-all-target-headers.hmap -iquote /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-project-headers.hmap -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Products/Release/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/tapi-1100.0.11/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/dyld-733.6/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/llvm-8.0.1.src/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/cfe-8.0.1.src/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/abseil-cpp-20200225 -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/pstl/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/pstl/stdlib -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/tbb/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/corecrypto/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources-normal/x86_64 -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources/x86_64 -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources -Wall -F/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Products/Release -Wno-deprecated-declarations -Wno-unknown-pragmas -MMD -MT dependencies -MF /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/objc.d --serialize-diagnostics /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/objc.dia -c /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/ld/src/ld/passes/objc.cpp -o /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/objc.o

CompileC /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/macho_relocatable_file.o /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/ld/src/ld/parsers/macho_relocatable_file.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0 (in target 'zld' from project 'zld')
    cd /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/ld
    export LANG\=en_US.US-ASCII
    clang -x c++ -target x86_64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c++1z -stdlib\=libc++ -Wno-trigraphs -fpascal-strings -O3 -fno-common -mdynamic-no-pic -Wno-missing-field-initializers -Wmissing-prototypes -Wunreachable-code -Wno-non-virtual-dtor -Woverloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wno-uninitialized -Wunknown-pragmas -Wno-shadow -Wfour-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wsign-compare -Wno-shorten-64-to-32 -Wnewline-eof -Wno-c++11-extensions -DLD_VERS\=\"ld64-\" -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Wno-invalid-offsetof -g -msse4.2 -Wno-sign-conversion -Winfinite-recursion -Wmove -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -iquote /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-generated-files.hmap -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-own-target-headers.hmap -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-all-target-headers.hmap -iquote /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-project-headers.hmap -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Products/Release/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/tapi-1100.0.11/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/dyld-733.6/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/llvm-8.0.1.src/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/cfe-8.0.1.src/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/abseil-cpp-20200225 -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/pstl/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/pstl/stdlib -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/tbb/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/corecrypto/include -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources-normal/x86_64 -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources/x86_64 -I/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources -Wall -F/tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Products/Release -Wno-deprecated-declarations -Wno-unknown-pragmas -MMD -MT dependencies -MF /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/macho_relocatable_file.d --serialize-diagnostics /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/macho_relocatable_file.dia -c /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/ld/src/ld/parsers/macho_relocatable_file.cpp -o /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/macho_relocatable_file.o

** BUILD FAILED **


The following build commands failed:
	CompileC /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/order.o /tmp/zld-20220107-32767-mc6sm/zld-homebrew-fixes-1.3.3/ld/src/ld/passes/order.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0
(1 failure)
make: *** [build_homebrew] Error 65

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/michaeleisel/homebrew-zld/issues
```

```bash
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15

xcodebuild -version
Xcode 12.2
Build version 12B45b
```

**Comment by michaeleisel** [comment] 2022-01-19 15:47
I'm unable to reproduce this issue. For order.cpp I see:
```
/bin/bash /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -x c++ -target x86_64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c++1z -stdlib\=libc++ -Wno-trigraphs -fpascal-strings -O3 -fno-common -mdynamic-no-pic -Wno-missing-field-initializers -Wmissing-prototypes -Wunreachable-code -Wno-non-virtual-dtor -Woverloaded-virtual -Wno-exit-time-destructors -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wno-uninitialized -Wunknown-pragmas -Wno-shadow -Wfour-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wsign-compare -Wno-shorten-64-to-32 -Wnewline-eof -Wno-c++11-extensions -DLD_VERS\=\"ld64-\" -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Wno-invalid-offsetof -g -msse4.2 -Wno-sign-conversion -Winfinite-recursion -Wmove -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -iquote /tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-generated-files.hmap -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-own-target-headers.hmap -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-all-target-headers.hmap -iquote /tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/zld-project-headers.hmap -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Products/Release/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/include -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/tapi-1100.0.11/include -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/dyld-733.6/include -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/llvm-8.0.1.src/include -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/cfe-8.0.1.src/include -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/abseil-cpp-20200225 -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/pstl/include -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/pstl/stdlib -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/tbb/include -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/corecrypto/include -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources-normal/x86_64 -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources/x86_64 -I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/DerivedSources -Wall -F/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Products/Release -Wno-deprecated-declarations -Wno-unknown-pragmas -MMD -MT dependencies -MF /tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/order.d --serialize-diagnostics /tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/order.dia -c /tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/ld/src/ld/passes/order.cpp -o /tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/order.o
```

which uses `-I/tmp/zld-20220119-75597-1wgyeb8/zld-homebrew-fixes-1.3.3/pstl/include` for headers like that one

**Comment by michaeleisel** [comment] 2022-01-19 16:13
one thing you could try, though, is upgrading xcode to 13. not sure if that would help, but it's the only thing a bit unusual about your setup

**Comment by michaeleisel** [comment] 2022-01-31 14:33
closing for now, feel free to update and i'll reopen

**Closed by michaeleisel** 2022-01-31 14:33 UTC
