### ISSUE TITLE
zld can't autolink libswiftCompatibility50.a

### ISSUE THREAD

**Issue by qyang-nj** [michaeleisel/zld#20] opened 2020-03-05 03:58 UTC
In some cases, `zld` isn't able to autolink `libswiftCompatibility50.a` and `libswiftCompatibilityDynamicReplacements.a`. 
```
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_foo in foo.a(foo.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_foo)
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_foo in foo.a(foo.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_foo)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I added the sample code to reproduce this problem. https://github.com/qyang-nj/zld-autolinking-issue

**Comment by michaeleisel** [comment] 2020-03-05 04:35
Possibly related to https://github.com/michaeleisel/zld/issues/16

**Comment by keith** [comment] 2020-03-05 04:44
Yea considering this was added alongside Swift ABI stuff I bet there's special handling for this that isn't in the open source dump.

**Comment by qyang-nj** [comment] 2020-03-05 05:08
> Possibly related to #16

Not sure, I already have `-all_load`.

**Comment by michaeleisel** [comment] 2020-03-05 16:33
Yeah, I think you're right. `-Wl,-why_load` shows:
```
...
__swift_FORCE_LOAD_$_swiftCompatibility50 forced load of /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCompatibility50.a(Overrides.cpp.o)
...
```

So this appears to be a directive to the linker. But, I can't find the string `FORCE_LOAD` in Xcode 11's `ld` binary. So, I'm unsure what *exactly* is going on. But I can certainly add support for it by just checking symbols for having `__swift_FORCE_LOAD_$...` unless anyone has further ideas on a different plan

**Comment by michaeleisel** [comment] 2020-03-05 16:40
I'm also curious, however we fix this, in what situations this is a problem. I'm working on a project right now with lots of static Swift 5 libraries, and it doesn't seem to have this problem

**Comment by qyang-nj** [comment] 2020-03-05 17:27
I ran into this issue immediately after switching to `zld` in the Airbnb main app and it's always reproducible. Then I tried to reproduce it in a minimum codebase. It seems for some cases `zld` can link `swiftCompatibility50` correctly. I'm still not sure what triggers this problem.

The solution sounds reasonable to me. Besides the problem, I'm also interested in how Swift autolinking is implemented. From [this code](https://github.com/apple/swift/blob/ab56d0df0024a3c4668f492636dd3a4353e7592d/stdlib/toolchain/Compatibility50/Overrides.cpp#L40), it seems `__swift_FORCE_LOAD` is the way, but I can't confirm.

**Comment by rmaz** [comment] 2020-03-10 17:42
I am seeing this occasionally after applying a fix for #16.

**Comment by rmaz** [comment] 2020-03-10 19:50
I believe the issue is this: https://github.com/michaeleisel/zld/blob/master/ld/src/ld/InputFiles.cpp#L668

Auto linked libraries do not seem to follow the same codepath as standard archives. Need to investigate why not. Can confirm adding `-force_load_swift_libs` fixes the issue for us.

**Comment by michaeleisel** [comment] 2020-03-18 01:23
@qyang-nj can you test and see if it's fixed in latest master?

**Comment by qyang-nj** [comment] 2020-03-18 04:07
Unfortunately, I see a bunch of linker errors with the latest master `zld`. It seems it wasn't able to link Foundation. I double checked with the default `ld`, it worked fine.

![image](https://user-images.githubusercontent.com/6559265/76924220-e681c680-6892-11ea-932a-c2add246565d.png)

**Comment by michaeleisel** [comment] 2020-03-19 19:29
@qyang-nj https://github.com/michaeleisel/zld/pull/33 uses a new approach that, with the new merging of the new ld-512 source code, fixes zld-autolinking-issue. can you take another look?

**Comment by qyang-nj** [comment] 2020-03-20 06:19
Confirmed. The latest master fixed the issue on both the demo code and our main app. Thanks!

**Closed** 2020-03-20 15:10 UTC
