### ISSUE TITLE
"make" fails through release package

### ISSUE THREAD

**Issue by Vrixyz** [michaeleisel/zld#68] opened 2020-10-17 20:17 UTC
I downloaded source files via zip, when entering `make`, this error pops up:

`ld: file not found: /Users/vrixyz/Downloads/zld/ld/../abseil-cpp-20200225/build/libabsl.a`

<details>
  <summary>Click to see more</summary>

  ```
35 warnings generated.

Ld /Users/vrixyz/Downloads/zld/build/Build/Products/Release/zld normal (in target 'zld' from project 'zld')
    cd /Users/vrixyz/Downloads/zld/ld
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/vrixyz/Downloads/zld/build/Build/Products/Release -L/Users/vrixyz/Downloads/zld/ld -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/system -F/Users/vrixyz/Downloads/zld/build/Build/Products/Release -filelist /Users/thierryberger/Downloads/zld/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/zld.LinkFileList -Xlinker -rpath -Xlinker @executable_path -Xlinker -rpath -Xlinker /var/db/xcode_select_link/Toolchains/XcodeDefault.xctoolchain/usr/lib -Xlinker -rpath -Xlinker /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib -Xlinker -rpath -Xlinker /usr/local/lib -dead_strip -Xlinker -object_path_lto -Xlinker /Users/vrixyz/Downloads/zld/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/zld_lto.o -stdlib\=libc++ -fobjc-link-runtime -Wl,-U,_malloc_default_purgeable_zone -Wl,-t -Wl,-U,_fnd_get_demangled_name -Wl,-client_name,ld -Wl,-alias,_zldVersionString,_ldVersionString -Wl,-all_load -Wl,/Users/vrixyz/Downloads/zld/ld/../abseil-cpp-20200225/build/libabsl.a -stdlib\=libc++ -lxar -Wl,-lazy_library,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -Wl,-exported_symbol,__mh_execute_header -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib -ltapi -Wl,-stack_size,0x01000000 -lLTO -ltbb -lswiftDemangle -Xlinker -dependency_info -Xlinker /Users/vrixyz/Downloads/zld/build/Build/Intermediates.noindex/zld.build/Release/zld.build/Objects-normal/x86_64/zld_dependency_info.dat -o /Users/vrixyz/Downloads/zld/build/Build/Products/Release/zld
ld: file not found: /Users/vrixyz/Downloads/zld/ld/../abseil-cpp-20200225/build/libabsl.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/vrixyz/Downloads/zld/build/Build/Products/Release/zld normal
(1 failure)
make: *** [build] Error 65

  ```

</details>

Upon inspection,  `zld/abseil-cpp-20200225/build/libabsl.a` is indeed missing.

Then, when attempting to `make abseil-cpp-20200225`, this error comes up:
```
fatal: not a git repository (or any of the parent directories): .git
make: `abseil-cpp-20200225' is up to date.
```

`make` via a fresh `git clone` succeeded from first try.

I would have expected the release package zip to be usable as advertised from the Readme.

**Comment by bjorn3** [comment] 2020-10-17 20:47
This is probably caused by https://github.com/michaeleisel/zld/blob/09ea158feae41f1965784d3cc26e571f7a3f6c84/Makefile#L30

**Comment by michaeleisel** [comment] 2020-10-17 20:58
@bjorn3 good point about that being the root cause. i'll probably leave that alone for now though and focus on just supporting `make`

@Vrixyz i'm unable to reproduce the issue. things work for me both with git clone and downloading the zip. can you share your full build log?

**Comment by Vrixyz** [comment] 2020-10-19 12:19
I succeeded in reproducing:
- uninstall cmake: `brew uninstall cmake`
- attempt to `make`
  - Fails to build, and see prompt to install `cmake`
- install cmake: `brew install cmake`
- `make`
- error `ld: file not found: /Users/thierryberger/Downloads/zld-1.2.1 2/ld/../abseil-cpp-20200225/build/libabsl.a`
- See full log: https://gist.github.com/Vrixyz/5567a962caf18b66d6da112b2d63c7d1

As you can see, this error actually happened because I hadn't cmake installed at first. I would have expected it to correctly make after the second `make` though.

**Comment by michaeleisel** [comment] 2020-10-20 12:06
fixed with https://github.com/michaeleisel/zld/commit/4b1d15f6a33b462e83b2bf0b110a250c88a6d7ce

**Closed by michaeleisel** 2020-10-20 12:06 UTC
